# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  sdkversion: '5.x'

steps:
- task: UseDotNet@2
  inputs:
    version: '$(sdkversion)'
    performMultiLevelLookup: true
    includePreviewVersions: true

- task: Npm@1
  displayName: 'install npm'
  inputs:
    verbose: false
  
- script: './node_modules/.bin/node-sass wwwroot --output wwwroot'
  displayName: 'Compile Sass assets'
  
- task: gulp@1
  displayName: 'Run gulp tasks'

- task: DotNetCoreCLI@2
  displayName: 'restore package dependencies'
  inputs:
    command: 'Restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*/*.csproj'
    arguments: '--no-restore --configuration $(buildConfiguration)'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --output/$(Build.ArtifactStagingDirectory)/$(buildConfiguration)'


